#include "scoap.h"
#define END_OF_DEF ,{ __MAX_ENTITY, "__MAX_ENTITY" }
struct StdCellInfo eInfo[] =
{
	{ STD180,{ { DUMMY,"C_ASSIGN" }
	END_OF_DEF
	} ,
	1,1,
	{ { PRIMARY_IN, "IN" } },
	{ { PRIMARY_OUT, "OUT" } }
	},

	{ STD180,{ { BUFXL,"BUFXL" },{ BUFX1,"BUFX1" },{ BUFX2,"BUFX2" },{ BUFX3,"BUFX3" },{ BUFX4,"BUFX4" },
	{ BUFX8,"BUFX8" },{ BUFX12,"BUFX12" },{ BUFX16,"BUFX16" },{ BUFX20,"BUFX20" },
	{ CLKBUFXL, "CLKBUFXL" },{ CLKBUFX1, "CLKBUFX1" },{ CLKBUFX2, "CLKBUFX2" },{ CLKBUFX3, "CLKBUFX3" },{ CLKBUFX4, "CLKBUFX4" },
	{ CLKBUFX8, "CLKBUFX8" },{ CLKBUFX12, "CLKBUFX12" },{ CLKBUFX16, "CLKBUFX16" },{ CLKBUFX20, "CLKBUFX20" },
	{ CLKINVXL, "CLKINVXL" },{ CLKINVX1, "CLKINVX1" },{ CLKINVX2, "CLKINVX2" },{ CLKINVX3, "CLKINVX3" },{ CLKINVX4, "CLKINVX4" },
	{ CLKINVX8, "CLKINVX8" },{ CLKINVX12, "CLKINVX12" },{ CLKINVX16, "CLKINVX16" },{ CLKINVX20, "CLKINVX20" },
	{ DLY1X1, "DLY1X1" },{ DLY2X1, "DLY2X1" },{ DLY3X1, "DLY3X1" },{ DLY4X1, "DLY4X1" },
	{ INVXL, "INVXL" },{ INVX1, "INVX1" },{ INVX2, "INVX2" },{ INVX3, "INVX3" },{ INVX4, "INVX4" },
	{ INVX8, "INVX8" },{ INVX12, "INVX12" },{ INVX16, "INVX16" },{ INVX20, "INVX20" }
	END_OF_DEF
	} ,
	1,1,
	{ { PRIMARY_IN, "A" } },
	{ { PRIMARY_OUT, "Y" } }
	},
	{ STD180,{ { TBUFXL, "TBUFXL" },{ TBUFX1, "TBUFX1" },{ TBUFX2, "TBUFX2" },{ TBUFX3, "TBUFX3" },{ TBUFX4, "TBUFX4" },
	{ TBUFX8, "TBUFX8" },{ TBUFX12, "TBUFX12" },{ TBUFX16, "TBUFX16" },{ TBUFX20, "TBUFX20" },
	{ TBUFIXL, "TBUFIXL" },{ TBUFIX1, "TBUFIX1" },{ TBUFIX2, "TBUFIX2" },{ TBUFIX3, "TBUFIX3" },{ TBUFIX4, "TBUFIX4" },
	{ TBUFIX8, "TBUFIX8" },{ TBUFIX12, "TBUFIX12" },{ TBUFIX16, "TBUFIX16" },{ TBUFIX20, "TBUFIX20" }
	END_OF_DEF
	},
	2, 1,
	{ { PRIMARY_IN, "A" },{ PRIMARY_IN, "OE" } },
	{ { PRIMARY_OUT, "Y" } }
	},

	{ STD180,{ { AND2XL,"AND2XL" },{ AND2X1,"AND2X1" },{ AND2X2,"AND2X2" },{ AND2X4,"AND2X4" },
	{ NAND2XL, "NAND2XL" },{ NAND2X2, "NAND2X2" },{ NAND2X1, "NAND2X1" },{ NAND2X4, "NAND2X4" },
	{ NOR2XL, "NOR2XL" },{ NOR2X1, "NOR2X1" },{ NOR2X2, "NOR2X2" },{ NOR2X4, "NOR2X4" },
	{ OR2XL, "OR2XL" },{ OR2X1, "OR2X1" },{ OR2X2, "OR2X2" },{ OR2X4, "OR2X4" },
	{ XNOR2XL, "XNOR2XL" },{ XNOR2X1, "XNOR2X1" },{ XNOR2X2, "XNOR2X2" },{ XNOR2X4, "XNOR2X4" },
	{ XOR2XL, "XOR2XL" },{ XOR2X1, "XOR2X1" },{ XOR2X2, "XOR2X2" },{ XOR2X4, "XOR2X4" }
	END_OF_DEF
	},
	2,1,
	{ { PRIMARY_IN, "A" },{ PRIMARY_IN, "B" } },
	{ { PRIMARY_OUT, "Y" } }
	},
	{ STD180,{ { NAND2BXL, "NAND2BXL" },{ NAND2BX2, "NAND2BX2" },{ NAND2BX1, "NAND2BX1" },{ NAND2BX4, "NAND2BX4" },
	{ NOR2BXL, "NOR2BXL" },{ NOR2BX2, "NOR2BX2" },{ NOR2BX1, "NOR2BX1" },{ NOR2BX4, "NOR2BX4" }
	END_OF_DEF
	},
	2,1,
	{ { PRIMARY_IN, "AN" },{ PRIMARY_IN, "B" } },
	{ { PRIMARY_OUT, "Y" } }
	},
	{ STD180,{ { DFFHQXL, "DFFHQXL" },{ DFFHQX1, "DFFHQX1" },{ DFFHQX2, "DFFHQX2" },{ DFFHQX4, "DFFHQX4" }
	END_OF_DEF
	} ,
	2,1,
	{ { PRIMARY_IN, "D" },{ CLOCK, "CK" } },
	{ { PRIMARY_OUT, "Q" } }
	},
	{ STD180,{ { ADDHXL, "ADDHXL" },{ ADDHX1, "ADDHX1" },{ ADDHX2, "ADDHX2" },{ ADDHX4, "ADDHX4" }
	END_OF_DEF
	} ,
	2,2,
	{ { PRIMARY_IN, "A" },{ PRIMARY_IN, "B" } },
	{ { PRIMARY_OUT, "CO" },{ PRIMARY_OUT, "S" } }
	},
	{ STD180,{ { RSLATXL, "RSLATXL" },{ RSLATX1, "RSLATX1" },{ RSLATX2, "RSLATX2" },{ RSLATX4, "RSLATX4" }
	END_OF_DEF
	} ,
	2,2,
	{ { PRIMARY_IN, "R" },{ PRIMARY_IN, "S" } },
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	{ STD180,{ { RSLATNXL, "RSLATNXL" },{ RSLATNX1, "RSLATNX1" },{ RSLATNX2, "RSLATNX2" },{ RSLATNX4, "RSLATNX4" }
	END_OF_DEF
	} ,
	2,2,
	{ { PRIMARY_IN, "RN" },{ PRIMARY_IN, "SN" } },
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	{ STD180,{ { DFFXL, "DFFXL" },{ DFFX1, "DFFX1" },{ DFFX2, "DFFX2" },{ DFFX4, "DFFX4" }
	END_OF_DEF
	} ,
	2,2,
	{ { PRIMARY_IN, "D" },{ CLOCK, "CK" } },
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	{ STD180,{ { DFFNXL, "DFFNXL" },{ DFFNX1, "DFFNX1" },{ DFFNX2, "DFFNX2" },{ DFFNX4, "DFFNX4" }
	END_OF_DEF
	} ,
	2,2,
	{ { PRIMARY_IN, "D" },{ CLOCK, "CKN" } },
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	{ STD180,{ { TLATXL, "TLATXL" },{ TLATX1, "TLATX1" },{ TLATX2, "TLATX2" },{ TLATX4, "TLATX4" }
	END_OF_DEF
	} ,
	2, 2,
	{ { PRIMARY_IN, "D" } , { PRIMARY_IN, "GN" } },
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	{ STD180,{ { AND3XL, "AND3XL" },{ AND3X1, "AND3X1" },{ AND3X2, "AND3X2" },{ AND3X4, "AND3X4" },
	{ NAND3XL, "NAND3XL" },{ NAND3X2, "NAND3X2" },{ NAND3X1, "NAND3X1" },{ NAND3X4, "NAND3X4" },
	{ NOR3XL, "NOR3XL" },{ NOR3X2, "NOR3X2" },{ NOR3X1, "NOR3X1" },{ NOR3X4, "NOR3X4" },
	{ OR3XL, "OR3XL" },{ OR3X2, "OR3X2" },{ OR3X1, "OR3X1" },{ OR3X4, "OR3X4" }
	END_OF_DEF
	},
	3,1,
	{ { PRIMARY_IN, "A" },{ PRIMARY_IN, "B" },{ PRIMARY_IN, "C" } },
	{ { PRIMARY_OUT, "Y" } }
	},
	{ STD180,{ { NAND3BXL, "NAND3BXL" },{ NAND3BX2, "NAND3BX2" },{ NAND3BX1, "NAND3BX1" },{ NAND3BX4, "NAND3BX4" },
	{ NOR3BXL, "NOR3BXL" },{ NOR3BX2, "NOR3BX2" },{ NOR3BX1, "NOR3BX1" },{ NOR3BX4, "NOR3BX4" }
	END_OF_DEF
	},
	3,1,
	{ { PRIMARY_IN, "AN" },{ PRIMARY_IN, "B" },{ PRIMARY_IN, "C" } },
	{ { PRIMARY_OUT, "Y" } }
	},
	{ STD180,{ { AOI21XL,"AOI21XL" },{ AOI21X1,"AOI21X1" },{ AOI21X2,"AOI21X2" },{ AOI21X4,"AOI21X4" },
	{ OAI21XL, "OAI21XL" },{ OAI21X1, "OAI21X1" },{ OAI21X2, "OAI21X2" },{ OAI21X4, "OAI21X4" }
	END_OF_DEF
	} ,
	3,1,
	{ { PRIMARY_IN, "A0" },{ PRIMARY_IN, "A1" },{ PRIMARY_IN, "B0" } },
	{ { PRIMARY_OUT, "Y" } }
	},
	{ STD180,{ { AOI2BB1XL,"AOI2BB1XL" },{ AOI2BB1X1,"AOI2BB1X1" },{ AOI2BB1X2,"AOI2BB1X2" },{ AOI2BB1X4,"AOI2BB1X4" },
	{ OAI2BB1XL,"OAI2BB1XL" },{ OAI2BB1X1,"OAI2BB1X1" },{ OAI2BB1X2,"OAI2BB1X2" },{ OAI2BB1X4,"OAI2BB1X4" }
	END_OF_DEF
	} ,
	3,1,
	{ { PRIMARY_IN, "A0N" },{ PRIMARY_IN, "A1N" },{ PRIMARY_IN, "B0" } },
	{ { PRIMARY_OUT, "Y" } }
	},
	{ STD180,{ { MX2XL, "MX2XL" },{ MX2X1, "MX2X1" },{ MX2X2, "MX2X2" },{ MX2X4, "MX2X4" },
	{ MXI2XL, "MXI2XL" },{ MXI2X1, "MXI2X1" },{ MXI2X2, "MXI2X2" },{ MXI2X4, "MXI2X4" }
	END_OF_DEF
	},
	3,1,
	{ { PRIMARY_IN, "A" },{ PRIMARY_IN, "B" },{ PRIMARY_IN, "S0" } },
	{ { PRIMARY_OUT, "Y" } }
	},
	{ STD180,{ { DFFRHQXL, "DFFRHQXL" },{ DFFRHQX1, "DFFRHQX1" },{ DFFRHQX2, "DFFRHQX2" },{ DFFRHQX4, "DFFRHQX4" }
	END_OF_DEF
	},
	3, 1,
	{ { PRIMARY_IN, "D" },{ CLOCK, "CK" },{ ASYNC_RESET, "RN" } },
	{ { PRIMARY_OUT, "Q" } }
	},
	{ STD180,{ { DFFSHQXL, "DFFSHQXL" },{ DFFSHQX1, "DFFSHQX1" },{ DFFSHQX2, "DFFSHQX2" },{ DFFSHQX4, "DFFSHQX4" }
	END_OF_DEF
	} ,
	3,1,
	{ { PRIMARY_IN, "D" },{ CLOCK, "CK" },{ PRIMARY_IN, "SN" } },
	{ { PRIMARY_OUT, "Q" } }
	},
	{ STD180,{ { TTLATXL, "TTLATXL" },{ TTLATX1, "TTLATX1" },{ TTLATX2, "TTLATX2" },{ TTLATX4, "TTLATX4" }
	END_OF_DEF
	},
	3,1,
	{ { PRIMARY_IN, "D" } ,{ PRIMARY_IN, "OE" },{ PRIMARY_IN, "G" } },
	{ { PRIMARY_OUT, "QN" } }
	},
	{ STD180,{ { ADDFXL,"ADDFXL" },{ ADDFX1,"ADDFX1" },{ ADDFX2,"ADDFX2" },{ ADDFX4,"ADDFX4" },
	{ ADDFHXL, "ADDFHXL" },{ ADDFHX1, "ADDFHX1" },{ ADDFHX2, "ADDFHX2" },{ ADDFHX4, "ADDFHX4" }
	END_OF_DEF
	},
	3, 2,
	{ { PRIMARY_IN, "A" },{ PRIMARY_IN, "B" },{ PRIMARY_IN, "CI" } },
	{ { PRIMARY_OUT, "CO" },{ PRIMARY_OUT, "S" } }
	},
	{ STD180,{ { DFFNRXL, "DFFNRXL" },{ DFFNRX1, "DFFNRX1" },{ DFFNRX2, "DFFNRX2" },{ DFFNRX4, "DFFNSRX4" }
	END_OF_DEF
	} ,
	3,2,
	{ { PRIMARY_IN, "D" },{ CLOCK, "CKN" },{ ASYNC_RESET, "RN" } },
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	{ STD180,{ { DFFRXL, "DFFRXL" },{ DFFRX1, "DFFRX1" },{ DFFRX2, "DFFRX2" },{ DFFRX4, "DFFRX4" },
	{ DFFTRXL, "DFFTRXL" },{ DFFTRX1, "DFFTRX1" },{ DFFTRX2, "DFFTRX2" },{ DFFTRX4, "DFFTRX4" }
	END_OF_DEF
	} ,
	3,2,
	{ { PRIMARY_IN, "D" },{ CLOCK, "CK" },{ ASYNC_RESET, "RN" } },
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	{ STD180,{ { DFFSXL, "DFFSXL" },{ DFFSX1, "DFFSX1" },{ DFFSX2, "DFFSX2" },{ DFFSX4, "DFFSX4" }
	END_OF_DEF
	} ,
	3,2,
	{ { PRIMARY_IN, "D" },{ CLOCK, "CK" },{ PRIMARY_IN, "SN" } },
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	{ STD180,{ { DFFNSXL, "DFFNSXL" },{ DFFNSX1, "DFFNSX1" },{ DFFNSX2, "DFFNSX2" },{ DFFNSX4, "DFFNSX4" }
	END_OF_DEF
	} ,
	3,2,
	{ { PRIMARY_IN, "D" },{ CLOCK, "CKN" },{ PRIMARY_IN, "SN" } },
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	{ STD180,{ { EDFFXL, "EDFFXL" },{ EDFFX1, "EDFFX1" },{ EDFFX2, "EDFFX2" },{ EDFFX4, "EDFFX4" }
	END_OF_DEF
	} ,
	3,2,
	{ { PRIMARY_IN, "D" },{ CLOCK, "CK" },{ PRIMARY_IN, "E" } },
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	{ STD180,{ { JKFFXL, "JKFFXL" },{ JKFFX1, "JKFFX1" },{ JKFFX2, "JKFFX2" },{ JKFFX4, "JKFFX4" }
	END_OF_DEF
	} ,
	3,2,
	{ { PRIMARY_IN, "J" },{ PRIMARY_IN, "K" },{ CLOCK, "CK" } },
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	{ STD180,{ { TLATNRXL, "TLATNRXL" },{ TLATNRX1, "TLATNRX1" },{ TLATNRX2, "TLATNRX2" },{ TLATNRX4, "TLATNRX4" }
	END_OF_DEF
	} ,
	3, 2,
	{ { PRIMARY_IN, "D" },{ PRIMARY_IN, "GN" },{ ASYNC_RESET, "RN" } },
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	{ STD180,{ { TLATRXL, "TLATRXL" },{ TLATRX1, "TLATRX1" },{ TLATRX2, "TLATRX2" },{ TLATRX4, "TLATRX4" }
	END_OF_DEF
	} ,
	3, 2,
	{ { PRIMARY_IN, "D" },{ PRIMARY_IN, "G" },{ ASYNC_RESET, "RN" } },
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	{ STD180,{ { TLATNSXL, "TLATNSXL" },{ TLATNSX1, "TLATNSX1" },{ TLATNSX2, "TLATNSX2" },{ TLATNSX4, "TLATNSX4" }
	END_OF_DEF
	} ,
	3, 2,
	{ { PRIMARY_IN, "D" },{ PRIMARY_IN, "GN" },{ PRIMARY_IN, "SN" } },
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	{ STD180,{ { TLATSXL, "TLATSXL" },{ TLATSX1, "TLATSX1" },{ TLATSX2, "TLATSX2" },{ TLATSX4, "TLATNSX4" }
	END_OF_DEF
	} ,
	3, 2,
	{ { PRIMARY_IN, "D" },{ PRIMARY_IN, "G" },{ PRIMARY_IN, "SN" } },
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	{ STD180,{ { AND4XL, "AND4XL" },{ AND4X1, "AND4X1" },{ AND4X2, "AND4X2" },{ AND4X4, "AND4X4" },
	{ NAND4XL, "NAND4XL" },{ NAND4X1, "NAND4X1" },{ NAND4X2, "NAND4X2" },{ NAND4X4, "NAND4X4" },
	{ NOR4XL, "NOR4XL" },{ NOR4X1, "NOR4X1" },{ NOR4X2, "NOR4X2" },{ NOR4X4, "NOR4X4" },
	{ OR4XL, "OR4XL" },{ OR4X1, "OR4X1" },{ OR4X2, "OR4X2" },{ OR4X4, "OR4X4" }
	END_OF_DEF
	} ,
	4, 1,
	{ { PRIMARY_IN, "A" },{ PRIMARY_IN, "B" },{ PRIMARY_IN, "C" },{ PRIMARY_IN, "D" } },
	{ { PRIMARY_OUT, "Y" } }
	},
	{ STD180,{ { NAND4BXL, "NAND4BXL" },{ NAND4BX1, "NAND4BX1" },{ NAND4BX2, "NAND4BX2" },{ NAND4BX4, "NAND4BX4" },
	{ NOR4BXL, "NOR4BXL" },{ NOR4BX1, "NOR4BX1" },{ NOR4BX2, "NOR4BX2" },{ NOR4BX4, "NOR4BX4" }
	END_OF_DEF
	} ,
	4, 1,
	{ { PRIMARY_IN, "AN" },{ PRIMARY_IN, "B" },{ PRIMARY_IN, "C" },{ PRIMARY_IN, "D" } },
	{ { PRIMARY_OUT, "Y" } }
	},
	{ STD180,{ { NAND4BBXL, "NAND4BBXL" },{ NAND4BBX1, "NAND4BBX1" },{ NAND4BBX2, "NAND4BBX2" },{ NAND4BBX4, "NAND4BBX4" },
	{ NOR4BBXL, "NOR4BBXL" },{ NOR4BBX1, "NOR4BBX1" },{ NOR4BBX2, "NOR4BBX2" },{ NOR4BBX4, "NOR4BBX4" }
	END_OF_DEF
	} ,
	4, 1,
	{ { PRIMARY_IN, "AN" },{ PRIMARY_IN, "BN" },{ PRIMARY_IN, "C" },{ PRIMARY_IN, "D" } },
	{ { PRIMARY_OUT, "Y" } }
	},
	{ STD180,{ { AOI22XL,"AOI22XL" },{ AOI22X1,"AOI22X1" },{ AOI22X2,"AOI22X2" },{ AOI22X4,"AOI22X4" },
	{ OAI22XL,"OAI22XL" },{ OAI22X1,"OAI22X1" },{ OAI22X2,"OAI22X2" },{ OAI22X4,"OAI22X4" }
	END_OF_DEF
	} ,
	4,1,
	{ { PRIMARY_IN, "A0" },{ PRIMARY_IN, "A1" },{ PRIMARY_IN, "B0" },{ PRIMARY_IN, "B1" } },
	{ { PRIMARY_OUT, "Y" } }
	},
	{ STD180,{ { AOI211XL, "AOI211XL" },{ AOI211X1, "AOI211X1" },{ AOI211X2, "AOI211X2" },{ AOI211X4, "AOI211X4" },
	{ OAI211XL, "OAI211XL" },{ OAI211X1, "OAI211X1" },{ OAI211X2, "OAI211X2" },{ OAI211X4, "OAI211X4" }
	END_OF_DEF
	} ,
	4,1,
	{ { PRIMARY_IN, "A0" },{ PRIMARY_IN, "A1" },{ PRIMARY_IN, "B0" },{ PRIMARY_IN, "C0" } },
	{ { PRIMARY_OUT, "Y" } }
	},
	{ STD180,{ { AOI2BB2XL,"AOI2BB2XL" },{ AOI2BB2X1,"AOI2BB2X1" },{ AOI2BB2X2,"AOI2BB2X2" },{ AOI2BB2X4,"AOI2BB2X4" },
	{ OAI2BB2XL,"OAI2BB2XL" },{ OAI2BB2X1,"OAI2BB2X1" },{ OAI2BB2X2,"OAI2BB2X2" },{ OAI2BB2X4,"OAI2BB2X4" }
	END_OF_DEF
	} ,
	4,1,
	{ { PRIMARY_IN, "A0N" },{ PRIMARY_IN, "A1N" },{ PRIMARY_IN, "B0" },{ PRIMARY_IN, "B1" } },
	{ { PRIMARY_OUT, "Y" } }
	},
	{ STD180,{ { AOI31XL,"AOI31XL" },{ AOI31X1,"AOI31X1" },{ AOI31X2,"AOI31X2" },{ AOI31X4,"AOI31X4" },
	{ OAI31XL,"OAI31XL" },{ OAI31X1,"OAI31X1" },{ OAI31X2,"OAI31X2" },{ OAI31X4,"OAI31X4" }
	END_OF_DEF
	} ,
	4,1,
	{ { PRIMARY_IN, "A0" },{ PRIMARY_IN, "A1" },{ PRIMARY_IN, "A2" },{ PRIMARY_IN, "B0" } },
	{ { PRIMARY_OUT, "Y" } }
	},
	{ STD180,{ { DFFSRHQXL, "DFFSRHQXXL" },{ DFFSRHQX1, "DFFSRHQXX1" },{ DFFSRHQX2, "DFFSRHQXX2" },{ DFFSRHQX4, "DFFSRHQXX4" }
	END_OF_DEF
	} ,
	4,1,
	{ { PRIMARY_IN, "D" },{ CLOCK, "CKN" },{ ASYNC_RESET, "RN" },{ PRIMARY_IN, "SN" } },
	{ { PRIMARY_OUT, "Q" } }
	},
	{ STD180,{ { SDFFHQXL, "SDFFHQXL" },{ SDFFHQX1, "SDFFHQX1" },{ SDFFHQX2, "SDFFHQX2" },{ SDFFHQX4, "SDFFHQX4" }
	END_OF_DEF
	} ,
	4,1,
	{ { PRIMARY_IN, "D" },{ CLOCK, "CK" },{ PRIMARY_IN, "SE" },{ PRIMARY_IN, "SI" } },
	{ { PRIMARY_OUT, "Q" } }
	},
	{ STD180,{ { SDFFXL, "SDFFXL" },{ SDFFX1, "SDFFX1" },{ SDFFX2, "SDFFX2" },{ SDFFX4, "SDFFX4" }
	END_OF_DEF
	} ,
	4,2,
	{ { PRIMARY_IN, "D" } ,{ CLOCK, "CK" }, { PRIMARY_IN, "SE" },{ PRIMARY_IN, "SI" } },
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	{ STD180,{ { SDFFNXL, "SDFFNXL" },{ SDFFNX1, "SDFFNX1" },{ SDFFNX2, "SDFFNX2" },{ SDFFNX4, "SDFFNX4" }
	END_OF_DEF
	} ,
	4,2,
	{ { PRIMARY_IN, "D" },{ CLOCK, "CKN" },{ PRIMARY_IN, "SE" },{ PRIMARY_IN, "SI" } },
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	{ STD180,{ { DFFNSRXL, "DFFNSRXL" },{ DFFNSRX1, "DFFNSRX1" },{ DFFNSRX2, "DFFNSRX2" },{ DFFNSRX4, "DFFNSRX4" }
	END_OF_DEF
	} ,
	4,2,
	{ { PRIMARY_IN, "D" },{ CLOCK, "CKN" },{ ASYNC_RESET, "RN" },{ PRIMARY_IN, "SN" } },
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	{ STD180,{ { DFFSRXL, "DFFSRXL" },{ DFFSRX1, "DFFSRX1" },{ DFFSRX2, "DFFSRX2" },{ DFFSRX4, "DFFSRX4" }
	END_OF_DEF
	} ,
	4,2,
	{ { PRIMARY_IN, "D" },{ CLOCK, "CKN" },{ ASYNC_RESET, "RN" },{ PRIMARY_IN, "SN" } },
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	{ STD180,{ { EDFFTRXL, "EDFFTRXL" },{ EDFFTRX1, "EDFFTRX1" },{ EDFFTRX2, "EDFFTRX2" },{ EDFFTRX4, "EDFFTRX4" }
	END_OF_DEF
	} ,
	4,2,
	{ { PRIMARY_IN, "D" },{ CLOCK, "CK" },{ ASYNC_RESET, "RN" },{ PRIMARY_IN, "E" } },
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	{ STD180,{ { JKFFRXL, "JKFFRXL" },{ JKFFRX1, "JKFFRX1" },{ JKFFRX2, "JKFFRX2" },{ JKFFRX4, "JKFFRX4" }
	END_OF_DEF
	} ,
	4,2,
	{ { PRIMARY_IN, "J" },{ PRIMARY_IN, "K" },{ CLOCK, "CK" },{ ASYNC_RESET, "RN" } },
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	{ STD180,{ { JKFFSXL, "JKFFSXL" },{ JKFFSX1, "JKFFSX1" },{ JKFFSX2, "JKFFSX2" },{ JKFFSX4, "JKFFSX4" }
	END_OF_DEF
	} ,
	4,2,
	{ { PRIMARY_IN, "J" },{ PRIMARY_IN, "K" },{ CLOCK, "CK" },{ PRIMARY_IN, "SN" } },
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	{ STD180,{ { TLATNSRXL, "TLATNSRXL" },{ TLATNSRX1, "TLATNSRX1" },{ TLATNSRX2, "TLATNSRX2" },{ TLATNSRX4, "TLATNSRX4" }
	END_OF_DEF
	} ,
	4, 2,
	{ { PRIMARY_IN, "D" },{ PRIMARY_IN, "GN" },{ ASYNC_RESET, "RN" },{ PRIMARY_IN, "SN" } },
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	{ STD180,{ { TLATSRXL, "TLATSRXL" },{ TLATSRX1, "TLATSRX1" },{ TLATSRX2, "TLATSRX2" },{ TLATSRX4, "TLATSRX4" }
	END_OF_DEF
	} ,
	4, 2,
	{ { PRIMARY_IN, "D" },{ PRIMARY_IN, "G" },{ ASYNC_RESET, "RN" },{ PRIMARY_IN, "SN" } },
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	{ STD180,{ { AOI221XL, "AOI221XL" },{ AOI221X1, "AOI221X1" },{ AOI221X2, "AOI221X2" },{ AOI221X4, "AOI221X4" },
	{ OAI221XL, "OAI221XL" },{ OAI221X1, "OAI221X1" },{ OAI221X2, "OAI221X2" },{ OAI221X4, "OAI221X4" }
	END_OF_DEF
	},
	5,1,
	{ { PRIMARY_IN, "A0" },{ PRIMARY_IN, "A1" },{ PRIMARY_IN, "B0" },{ PRIMARY_IN, "B1" },{ PRIMARY_IN, "C0" } },
	{ { PRIMARY_OUT, "Y" } }
	},
	{ STD180,{ { AOI32XL, "AOI32XL" },{ AOI32X1, "AOI32X1" },{ AOI32X2, "AOI32X2" },{ AOI32X4, "AOI32X4" },
	{ OAI32XL, "OAI32XL" },{ OAI32X1, "OAI32X1" },{ OAI32X2, "OAI32X2" },{ OAI32X4, "OAI32X4" }
	END_OF_DEF
	},
	5,1,
	{ { PRIMARY_IN, "A0" },{ PRIMARY_IN, "A1" },{ PRIMARY_IN, "B0" },{ PRIMARY_IN, "B1" },{ PRIMARY_IN, "A2" } },
	{ { PRIMARY_OUT, "Y" } }
	},
	{ STD180,{ { SDFFRHQXL, "SDFFRHQXL" },{ SDFFRHQX1, "SDFFRHQX1" },{ SDFFRHQX2, "SDFFRHQX2" },{ SDFFRHQX4, "SDFFRHQX4" }
	END_OF_DEF
	} ,
	5,1,
	{ { PRIMARY_IN, "D" },{ CLOCK, "CK" },{ PRIMARY_IN, "SE" },{ PRIMARY_IN, "SI" },{ ASYNC_RESET, "RN" } },
	{ { PRIMARY_OUT, "Q" } }
	},
	{ STD180,{ { SDFFSHQXL, "SDFFSHQXL" },{ SDFFSHQX1, "SDFFSHQX1" },{ SDFFSHQX2, "SDFFSHQX2" },{ SDFFSHQX4, "SDFFSHQX4" }
	END_OF_DEF
	} ,
	5,1,
	{ { PRIMARY_IN, "D" },{ CLOCK, "CK" },{ PRIMARY_IN, "SE" },{ PRIMARY_IN, "SI" },{ PRIMARY_IN, "SN" } },
	{ { PRIMARY_OUT, "Q" } }
	},
	{ STD180,{ { SEDFFHQXL, "SEDFFHQXL" },{ SEDFFHQX1, "SEDFFHQX1" },{ SEDFFHQX2, "SEDFFHQX2" },{ SEDFFHQX4, "SEDFFHQX4" }
	END_OF_DEF
	} ,
	5,1,
	{ { PRIMARY_IN, "D" },{ CLOCK, "CK" },{ PRIMARY_IN, "SE" },{ PRIMARY_IN, "SI" },{ PRIMARY_IN, "SN" } },
	{ { PRIMARY_OUT, "Q" } }
	},
	{ STD180,{ { JKFFSRXL, "JKFFSRXL" },{ JKFFSRX1, "JKFFSRX1" },{ JKFFSRX2, "JKFFSRX2" },{ JKFFSRX4, "JKFFSRX4" }
	END_OF_DEF
	} ,
	5,2,
	{ { PRIMARY_IN, "J" },{ PRIMARY_IN, "K" },{ CLOCK, "CK" },{ ASYNC_RESET, "RN" },{ PRIMARY_IN, "SN" } },
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	{ STD180,{ { SDFFNRXL, "SDFFNRXL" },{ SDFFNRX1, "SDFFNRX1" },{ SDFFNRX2, "SDFFNRX2" },{ SDFFNRX4, "SDFFNRX4" }
	END_OF_DEF
	} ,
	5,2,
	{ { PRIMARY_IN, "D" },{ CLOCK, "CKN" },{ PRIMARY_IN, "SE" },{ PRIMARY_IN, "SI" },{ ASYNC_RESET, "RN" } },
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	{ STD180,{ { SDFFRXL, "SDFFRXL" },{ SDFFRX1, "SDFFRX1" },{ SDFFRX2, "SDFFRX2" },{ SDFFRX4, "SDFFRX4" },
	{ SDFFTRXL, "SDFFTRXL" },{ SDFFTRX1, "SDFFTRX1" },{ SDFFTRX2, "SDFFTRX2" },{ SDFFTRX4, "SDFFTRX4" }
	END_OF_DEF
	} ,
	5,2,
	{ { PRIMARY_IN, "D" },{ CLOCK, "CK" },{ PRIMARY_IN, "SE" },{ PRIMARY_IN, "SI" },{ ASYNC_RESET, "RN" } },
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	{ STD180,{ { SDFFNSXL, "SDFFNSXL" },{ SDFFNSX1, "SDFFNSX1" },{ SDFFNSX2, "SDFFNSX2" },{ SDFFNSX4, "SDFFNSX4" } } ,
	5,2,
	{ { PRIMARY_IN, "D" },{ CLOCK, "CKN" },{ PRIMARY_IN, "SE" },{ PRIMARY_IN, "SI" },{ PRIMARY_IN, "SN" } },
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	{ STD180,{ { SDFFSXL, "SDFFSXL" },{ SDFFSX1, "SDFFSX1" },{ SDFFSX2, "SDFFSX2" },{ SDFFSX4, "SDFFSX4" }
	END_OF_DEF
	} ,
	5,2,
	{ { PRIMARY_IN, "D" },{ CLOCK, "CK" },{ PRIMARY_IN, "SE" },{ PRIMARY_IN, "SI" },{ PRIMARY_IN, "SN" } },
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	{ STD180,{ { SEDFFXL, "SEDFFXL" },{ SEDFFX1, "SEDFFX1" },{ SEDFFX2, "SEDFFX2" },{ SEDFFX4, "SEDFFX4" }
	END_OF_DEF
	} ,
	5,2,
	{ { PRIMARY_IN, "D" },{ CLOCK, "CK" },{ PRIMARY_IN, "SE" },{ PRIMARY_IN, "SI" },{ PRIMARY_IN, "E" } },
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	{ STD180,{ { AOI222XL, "AOI222XL" },{ AOI222X1, "AOI222X1" },{ AOI222X2, "AOI222X2" },{ AOI222X4, "AOI222X4" },
	{ OAI222XL, "OAI222XL" },{ OAI222X1, "OAI222X1" },{ OAI222X2, "OAI222X2" },{ OAI222X4, "OAI222X4" }
	END_OF_DEF
	},
	6,1,
	{ { PRIMARY_IN, "A0" },{ PRIMARY_IN, "A1" },{ PRIMARY_IN, "B0" },{ PRIMARY_IN, "B1" },{ PRIMARY_IN, "C0" },{ PRIMARY_IN, "C1" } },
	{ { PRIMARY_OUT, "Y" } }
	},
	{ STD180,{ { AOI33XL, "AOI33XL" },{ AOI33X1, "AOI33X1" },{ AOI33X2, "AOI33X2" },{ AOI33X4, "AOI33X4" },
	{ OAI33XL, "OAI33XL" },{ OAI33X1, "OAI33X1" },{ OAI33X2, "OAI33X2" },{ OAI33X4, "OAI33X4" }
	END_OF_DEF
	},
	6,1,
	{ { PRIMARY_IN, "A0" },{ PRIMARY_IN, "A1" },{ PRIMARY_IN, "B0" },{ PRIMARY_IN, "B1" },{ PRIMARY_IN, "A2" },{ PRIMARY_IN, "B2" } },
	{ { PRIMARY_OUT, "Y" } }
	},
	{ STD180,{ { MX4XL, "MX4XL" },{ MX4X1, "MX4X1" },{ MX4X2, "MX4X2" },{ MX4X4, "MX4X4" },
	{ MXI4XL, "MXI4XL" },{ MXI4X1, "MXI4X1" },{ MXI4X2, "MXI4X2" },{ MXI4X4, "MXI4X4" }
	END_OF_DEF
	},
	6,1,
	{ { PRIMARY_IN, "A" },{ PRIMARY_IN, "B" },{ PRIMARY_IN, "C" },{ PRIMARY_IN, "D" },
	{ PRIMARY_IN, "S0" },{ PRIMARY_IN, "S1" } },
	{ { PRIMARY_OUT, "Y" } }
	},
	{ STD180,{ { SDFFNSRXL, "SDFFNSRXL" },{ SDFFNSRX1, "SDFFNSRX1" },{ SDFFNSRX2, "SDFFNSRX2" },{ SDFFNSRX4, "SDFFNSRX4" }
	END_OF_DEF
	} ,
	6,2,
	{ { PRIMARY_IN, "D" },{ CLOCK, "CKN" },{ PRIMARY_IN, "SE" },{ PRIMARY_IN, "SI" },{ PRIMARY_IN, "SN" },{ ASYNC_RESET, "RN" } },
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	{ STD180,{ { SDFFSRXL, "SDFFSRXL" },{ SDFFSRX1, "SDFFSRX1" },{ SDFFSRX2, "SDFFSRX2" },{ SDFFSRX4, "SDFFSRX4" }
	END_OF_DEF
	} ,
	6,2,
	{ { PRIMARY_IN, "D" },{ CLOCK, "CK" },{ PRIMARY_IN, "SE" },{ PRIMARY_IN, "SI" },{ ASYNC_RESET, "RN" },{ PRIMARY_IN, "SN" } },
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	{ STD180,{ { SDFFSRHQXL, "SDFFSRHQXL" },{ SDFFSRHQX1, "SDFFSRHQX1" },{ SDFFSRHQX2, "SDFFSRHQX2" },{ SDFFSRHQX4, "SDFFSRHQX4" }
	END_OF_DEF
	} ,
	6,1,
	{ { PRIMARY_IN, "D" },{ CLOCK, "CKN" },{ PRIMARY_IN, "SE" },{ PRIMARY_IN, "SI" },{ PRIMARY_IN, "SN" },{ ASYNC_RESET, "RN" } },
	{ { PRIMARY_OUT, "Q" } }
	},
	{ STD180,{ { SEDFFTRXL, "SEDFFTRXL" },{ SEDFFTRX1, "SEDFFTRX1" },{ SEDFFTRX2, "SEDFFTRX2" },{ SEDFFTRX4, "SEDFFTRX4" }
	END_OF_DEF
	} ,
	6,2,
	{ { PRIMARY_IN, "D" },{ CLOCK, "CK" },{ PRIMARY_IN, "SE" },{ PRIMARY_IN, "SI" },{ PRIMARY_IN, "E" },{ ASYNC_RESET, "RN" } },
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	{ STD180,{ { DFFSRX1,"DFFSRX1" }
	END_OF_DEF
	} ,
	4, 2,
	{ { CLOCK, "CK" },{ PRIMARY_IN, "D" },{ PRIMARY_IN, "RN" },{ PRIMARY_IN, "SN" } },
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	{ STD90,{ { OAI33X1, "OAI33X1" }
	END_OF_DEF
	} ,
	6, 1,
	{ { PRIMARY_IN, "A0" },{ PRIMARY_IN, "B0" },{ PRIMARY_IN, "A1" },{ PRIMARY_IN, "B1" },{ PRIMARY_IN, "A2" },{ PRIMARY_IN, "B2" } },
	{ { PRIMARY_OUT, "Y" } }
	},

	{ STD90,{ { SDFFSRX1, "SDFFSRX1" }
	END_OF_DEF
	} ,
	6, 2,
	{ { PRIMARY_IN, "D" },{ CLOCK, "CK" },{ PRIMARY_IN, "SE" },{ PRIMARY_IN, "SI" },{ ASYNC_RESET, "RN" },{ PRIMARY_IN, "SN" } },
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	{ STD180,{ { TLATSRX1, "TLATSRX1" }
	END_OF_DEF
	} ,
	4, 2,
	{ { PRIMARY_IN, "D" },{ CLOCK, "G" },{ PRIMARY_IN, "RN" },{ PRIMARY_IN, "SN" } },
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	//part 2 : 90 nm
	{ STD90,{ { DUMMY,"C_ASSIGN" }
	END_OF_DEF
	} ,
	1,1,
	{ { PRIMARY_IN, "IN" } },
	{ { PRIMARY_OUT, "OUT" } }
	},
	{ STD90,{ { INVX0, "INVX0" },{ INVX1, "INVX1" },{ INVX2, "INVX2" },{ INVX4, "INVX4" },{ INVX8, "INVX8" },{ INVX16, "INVX16" },{ INVX32, "INVX32" },
	{ IBUFFX2,"IBUFFX2" },{ IBUFFX4,"IBUFFX4" },{ IBUFFX8,"IBUFFX8" },{ IBUFFX16,"IBUFFX16" },{ IBUFFX32, "IBUFFX32" }
	END_OF_DEF
	},
	1, 1,
	{ { PRIMARY_IN, "IN" } },
	{ { PRIMARY_OUT, "QN" } }
	},
	{ STD90,{ { NBUFFX2, "NBUFFX2" },{ NBUFFX4, "NBUFFX4" },{ NBUFFX8, "NBUFFX8" },{ NBUFFX16, "NBUFFX16" }
	END_OF_DEF
	},
	1,1,
	{ { PRIMARY_IN, "IN" } },
	{ { PRIMARY_OUT, "Q" } }
	},
	{ STD90,{ { TNBUFFX1, "TNBUFFX1" },{ TNBUFFX2, "TNBUFFX2" },{ TNBUFFX4, "TNBUFFX4" },{ TNBUFFX8, "TNBUFFX8" },{ TNBUFFX16, "TNBUFFX16" }
	END_OF_DEF
	},
	2,1,
	{ { PRIMARY_IN, "IN" },{ PRIMARY_IN, "ENB" } },
	{ { PRIMARY_OUT, "Q" } }
	},
	{ STD90,{ { AND2X4, "AND2X4" },{ AND2X2, "AND2X2" },{ AND2X1, "AND2X1" },
	{ XOR2X2, "XOR2X2" },{ XOR2X1, "XOR2X1" },
	{ XNOR2X1, "XNOR2X1" },{ XNOR2X2, "XNOR2X2" },
	{ OR2X1, "OR2X1" },{ OR2X2, "OR2X2" },{ OR2X4, "OR2X4" }
	END_OF_DEF
	},
	2,1,
	{ { PRIMARY_IN, "IN1" },{ PRIMARY_IN, "IN2" } },
	{ { PRIMARY_OUT, "Q" } }
	},
	{ STD90,{ { NAND2X0, "NAND2X0" },{ NAND2X1, "NAND2X1" },{ NAND2X2, "NAND2X2" },{ NAND2X4, "NAND2X4" },
	{ NOR2X0, "NOR2X0" },{ NOR2X1,"NOR2X1" },{ NOR2X2, "NOR2X2" },{ NOR2X4, "NOR2X4" }
	//{ XNOR2X1,"XNOR2X1" },{ XNOR2X2, "XNOR2X2" } deleted due to Ethernet Example
	END_OF_DEF
	} ,
	2,1,
	{ { PRIMARY_IN, "IN1" },{ PRIMARY_IN, "IN2" } },
	{ { PRIMARY_OUT, "QN" } }
	},
	{ STD90,{ { ISOLANDX1, "ISOLANDX1" },{ ISOLANDX2, "ISOLANDX2" },{ ISOLANDX4, "ISOLANDX4" },{ ISOLANDX8, "ISOLANDX8" },
	{ ISOLORX1, "ISOLORX1" },{ ISOLORX2, "ISOLORX2" },{ ISOLORX4, "ISOLORX4" },{ ISOLORX8, "ISOLORX8" }
	END_OF_DEF
	} ,
	2, 1,
	{ { PRIMARY_IN, "D" },{ PRIMARY_IN, "ISO" } },
	{ { PRIMARY_OUT, "Q" } }
	},
	{ STD90,{ { AND3X1,"AND3X1" },{ AND3X2,"AND3X2" },{ AND3X4, "AND3X4" },
	{ AO21X1, "AO21X1" },{ AO21X2, "AO21X2" },
	{ OA21X1,"OA21X1" },{ OA21X2,"OA21X2" },
	{ OR3X1, "OR3X1" },{ OR3X2,"OR3X2" },{ OR3X4, "OR3X4" },
	{ XNOR3X1, "XNOR3X1" },{ XNOR3X2, "XNOR3X2" },
	{ XOR3X1, "XOR3X1" },{ XOR3X2, "XOR3X2" }
	END_OF_DEF
	},
	3,1,
	{ { PRIMARY_IN, "IN1" },{ PRIMARY_IN, "IN2" },{ PRIMARY_IN, "IN3" } },
	{ { PRIMARY_OUT, "Q" } }
	},
	{ STD90,{ { NAND3X0, "NAND3X0" },{ NAND3X1, "NAND3X1" },{ NAND3X2, "NAND3X2" },{ NAND3X4, "NAND3X4" },
	{ NOR3X0, "NOR3X0" },{ NOR3X1, "NOR3X1" },{ NOR3X2, "NOR3X2" },{ NOR3X4, "NOR3X4" },
	//{ XNOR3X1, "XNOR3X1" },{ XNOR3X2, "XNOR3X2" },deleted due to s35932 Example
	{ AOI21X1,"AOI21X1" },{ AOI21X2, "AOI21X2" },
	{ OAI21X1,"OAI21X1" },{ OAI21X2,"OAI21X2" }
	END_OF_DEF
	},
	3,1,
	{ { PRIMARY_IN, "IN1" },{ PRIMARY_IN, "IN2" },{ PRIMARY_IN, "IN3" } },
	{ { PRIMARY_OUT, "QN" } }
	},
	{ STD90,{ { MUX21X1,"MUX21X1" },{ MUX21X2,"MUX21X2" }
	END_OF_DEF
	} ,
	3, 1,
	{ { PRIMARY_IN, "IN1" },{ PRIMARY_IN, "IN2" },{ PRIMARY_IN, "S" } },
	{ { PRIMARY_OUT, "Q" } }
	},
	{ STD90,{ { AND4X1,"AND4X1" },{ AND4X2,"AND4X2" },{ AND4X4, "AND4X4" },
	{ AO22X1,"AO22X1" },{ AO22X2,"AO22X2" },
	{ OA22X1, "OA22X1" },{ OA22X2, "OA22X2" },
	{ OR4X1, "OR4X1" },{ OR4X2,"OR4X2" },{ OR4X4,"OR4X4" }
	END_OF_DEF
	} ,
	4,1,
	{ { PRIMARY_IN, "IN1" },{ PRIMARY_IN, "IN2" },{ PRIMARY_IN, "IN3" },{ PRIMARY_IN, "IN4" } },
	{ { PRIMARY_OUT, "Q" } }
	},
	{ STD90,{ { NAND4X0, "NAND4X0" },{ NAND4X1, "NAND4X1" },
	{ NOR4X0, "NOR4X0" },{ NOR4X1, "NOR4X1" },
	{ AOI22X1, "AOI22X1" },{ AOI22X2, "AOI22X2" },
	{ OAI22X1, "OAI22X1" },{ OAI22X2, "OAI22X2" }
	END_OF_DEF
	},
	4,1,
	{ { PRIMARY_IN, "IN1" },{ PRIMARY_IN, "IN2" },{ PRIMARY_IN, "IN3" },{ PRIMARY_IN, "IN4" } },
	{ { PRIMARY_OUT, "QN" } }
	},
	{ STD90,{ { AO221X1,"AO221X1" },{ AO221X2,"AO221X2" },
	{ OA221X1,"OA221X1" },{ OA221X2,"OA221X2" }
	END_OF_DEF
	} ,
	5,1,
	{ { PRIMARY_IN, "IN1" },{ PRIMARY_IN, "IN2" },{ PRIMARY_IN, "IN3" },{ PRIMARY_IN, "IN4" },{ PRIMARY_IN, "IN5" } },
	{ { PRIMARY_OUT, "Q" } }
	},
	{ STD90,{ { AOI221X1, "AOI221X1" },{ AOI221X2, "AOI221X2" },
	{ OAI221X1, "OAI221X1" },{ OAI221X2, "OAI221X2" }
	END_OF_DEF
	} ,
	5,1,
	{ { PRIMARY_IN, "IN1" },{ PRIMARY_IN, "IN2" },{ PRIMARY_IN, "IN3" },{ PRIMARY_IN, "IN4" },{ PRIMARY_IN, "IN5" } },
	{ { PRIMARY_OUT, "QN" } }
	},
	{ STD90,{ { AO222X1,"AO222X1" },{ AO222X2,"AO222X2" },
	{ OA222X1,"OA222X1" },{ OA222X2,"OA222X2" }
	END_OF_DEF
	},
	6,1,
	{ { PRIMARY_IN, "IN1" },{ PRIMARY_IN, "IN2" },{ PRIMARY_IN, "IN3" },{ PRIMARY_IN, "IN4" },{ PRIMARY_IN, "IN5" },{ PRIMARY_IN, "IN6" } },
	{ { PRIMARY_OUT, "Q" } }
	},
	{ STD90,{ { AOI222X1,"AOI222X1" },{ AOI222X2,"AOI222X2" },
	{ OAI222X1,"OAI222X1" },{ OAI222X1, "OAI222X2" }
	END_OF_DEF
	},
	6,1,
	{ { PRIMARY_IN, "IN1" },{ PRIMARY_IN, "IN2" },{ PRIMARY_IN, "IN3" },{ PRIMARY_IN, "IN4" },{ PRIMARY_IN, "IN5" },{ PRIMARY_IN, "IN6" } },
	{ { PRIMARY_OUT, "QN" } }
	},
	{ STD90,{ { MUX41X1,"MUX41X1" },{ MUX41X2,"MUX41X2" }
	END_OF_DEF
	} ,
	6, 1,
	{ { PRIMARY_IN, "IN1" },{ PRIMARY_IN, "IN2" },{ PRIMARY_IN, "IN3" },{ PRIMARY_IN, "IN4" },
	{ PRIMARY_IN, "S0" },{ PRIMARY_IN, "S1" } },
	{ { PRIMARY_OUT, "Q" } }
	},
	{ STD90,{ { DFFX1, "DFFX1" },{ DFFX2, "DFFX2" },{ DFFNX1, "DFFNX1" },{ DFFNX2, "DFFNX2" },
	{ LATCHX1, "LATCHX1" },{ LATCHX2, "LATCHX2" }
	END_OF_DEF
	} ,
	2, 2,
	{ { PRIMARY_IN, "D" },{ CLOCK, "CLK" } },
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	{ STD90,{ { HADDX1, "HADDX1" },{ HADDX2, "HADDX2" }
	END_OF_DEF
	},
	2,2,
	{ { PRIMARY_IN, "A0" },{ PRIMARY_IN, "B0" } },
	{ { PRIMARY_OUT, "C1" },{ PRIMARY_OUT, "SO" } }
	},
	{ STD90,{ { LNANDX1, "LNANDX1" },{ LNANDX2, "LNANDX2" }
	END_OF_DEF
	},
	2,2,
	{ { PRIMARY_IN, "RIN" },{ PRIMARY_IN, "SIN" } },
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	//{ STD90,{ { DEC24X1,"DEC24X1" },{ DEC24X2, "DEC24X2" } },
	//2, 4,
	//{ { PRIMARY_IN, "IN1" },{ PRIMARY_IN, "IN2" } },
	//{ { PRIMARY_OUT, "Q0" },{ PRIMARY_OUT, "Q1" },{ PRIMARY_OUT, "Q2" },{ PRIMARY_OUT, "Q3" } }
	//},
	{ STD90,{ { FADDX1,"FADDX1" },{ FADDX2,"FADDX2" }
	END_OF_DEF
	} ,
	3,2,
	{ { PRIMARY_IN, "A" },{ PRIMARY_IN, "B" },{ PRIMARY_IN, "CI" } },
	{ { PRIMARY_OUT, "CO" },{ PRIMARY_OUT, "S" } }
	},
	{ STD90,{ { DFFASX1,"DFFASX1" },{ DFFASX2,"DFFASX2" },{ DFFNASX1, "DFFNASX1" },{ DFFNASX2, "DFFNASX2" },
	{ LASX1, "LASX1" },{ LASX2, "LASX2" }
	END_OF_DEF
	} ,
	3,2,
	{ { PRIMARY_IN, "D" },{ PRIMARY_IN, "SETB" },{ CLOCK, "CLK" } },
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	{ STD90,{ { DFFARX1,"DFFARX1" },{ DFFARX2,"DFFARX2" },{ DFFNARX1, "DFFNARX1" },{ DFFNARX2, "DFFNARX2" },
	{ LARX1, "LARX1" },{ LARX2, "LARX2" }
	END_OF_DEF
	} ,
	3,2,
	{ { PRIMARY_IN, "D" },{ ASYNC_RESET, "RSTB" },{ CLOCK, "CLK" } },
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	{ STD90,{ { LASRQX1, "LASRQX1" },{ LASRQX2, "LASRQX2" }
	END_OF_DEF
	},
	4,1,
	{ { PRIMARY_IN, "D" },{ PRIMARY_IN, "SETB" },{ ASYNC_RESET, "RSTB" },{ CLOCK, "CLK" } },
	{ { PRIMARY_OUT, "Q" } }
	},
	{ STD90,{ { LASRNX1, "LASRNX1" },{ LASRNX2, "LASRNX2" }
	END_OF_DEF
	},
	4,1,
	{ { PRIMARY_IN, "D" },{ PRIMARY_IN, "SETB" },{ ASYNC_RESET, "RSTB" },{ CLOCK, "CLK" } },
	{ { PRIMARY_OUT, "QN" } }
	},
	{ STD90,{ { DFFASRX1,"DFFASRX1" },{ DFFASRX2,"DFFASRX2" },{ DFFSSRX1, "DFFSSRX1" },{ DFFSSRX2, "DFFSSRX2" },
	{ DFFNASRX1, "DFFNASRX1" },{ DFFNASRX2, "DFFNASRX2" },{ DFFNASRQX1, "DFFNASRQX1" },{ DFFNASRQX2, "DFFNASRQX2" },
	{ DFFNASRNX1, "DFFNASRNX1" },{ DFFNASRNX2, "DFFNASRNX2" },{ LASRX1, "LASRX1" },{ LASRX2, "LASRX2" }
	END_OF_DEF
	} ,
	4,2,
	{ { PRIMARY_IN, "D" },{ PRIMARY_IN, "SETB" },{ ASYNC_RESET, "RSTB" },{ CLOCK, "CLK" } },
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	{ STD90,{ { SDFFX1,"SDFFX1" },{ SDFFX2,"SDFFX2" },{ SDFFNX1, "SDFFNX1" },{ SDFFNX2, "SDFFNX2" }
	END_OF_DEF
	} ,
	4, 2,
	{ { PRIMARY_IN, "D" },{ CLOCK, "CLK" },{ PRIMARY_IN, "SE" },{ PRIMARY_IN, "SI" } },
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	{ STD90,{ { SDFFASX1, "SDFFASX1" },{ SDFFASX2, "SDFFASX2" },{ SDFFNASX1, "SDFFNASX1" },{ SDFFNASX2, "SDFFNASX2" }
	END_OF_DEF
	},
	5,2,
	{ { PRIMARY_IN, "D" },{ PRIMARY_IN, "SE" },{ PRIMARY_IN, "SI" },{ CLOCK, "CLK" },{ PRIMARY_IN, "SETB" } },
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	{ STD90,{ { SDFFARX1, "SDFFARX1" },{ SDFFARX2, "SDFFARX2" },{ SDFFNARX1, "SDFFNARX1" },{ SDFFNARX2, "SDFFNARX2" }
	END_OF_DEF
	},
	5,2,
	{ { PRIMARY_IN, "D" },{ CLOCK, "CLK" } ,{ PRIMARY_IN, "SE" },{ PRIMARY_IN, "SI" },{ ASYNC_RESET, "RSTB" } },
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	{ STD90,{ { SDFFASRX1, "SDFFASRX1" },{ SDFFASRX2, "SDFFASRX2" },{ SDFFSSRX1, "SDFFSSRX1" },{ SDFFSSRX2, "SDFFSSRX2" },
	{ SDFFNASRX1, "SDFFNASRX1" },{ SDFFNASRX2, "SDFFNASRX2" }
	END_OF_DEF
	},
	6,2,
	{ { PRIMARY_IN, "D" },{ CLOCK, "CLK" },{ PRIMARY_IN, "SE" },{ PRIMARY_IN, "SI" },{ PRIMARY_IN, "SETB" },{ ASYNC_RESET, "RSTB" } }, //SETB is RESET??
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	},
	{ STD90,{ { SDFFASRSX1, "SDFFASRSX1" },{ SDFFASRSX2, "SDFFASRSX2" }
	END_OF_DEF
	},
	6,3,
	{ { PRIMARY_IN, "D" },{ PRIMARY_IN, "SE" },{ PRIMARY_IN, "SI" },{ CLOCK, "CLK" },{ PRIMARY_IN, "SETB" },{ ASYNC_RESET, "RSTB" } }, //SETB is RESET??
	{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" },{ PRIMARY_OUT, "S0" } }
	},
	{ STD90,{ { LSDNENX1, "LSDNENX1" },{ LSDNENX2, "LSDNENX2" },{ LSDNENX4, "LSDNENX4" },{ LSDNENX8, "LSDNENX8" }
	END_OF_DEF
	} ,
	2, 1,
	{ { PRIMARY_IN, "D" },{ PRIMARY_IN, "ENB" } },
	{ { PRIMARY_OUT, "Q" } }
	},
	{ STD90,{ { LSDNX1, "LSDNX1" },{ LSDNX2, "LSDNX2" },{ LSDNX4, "LSDNX4" },{ LSDNX8, "LSDNX8" }
	END_OF_DEF
	},
	1,1,
	{ { PRIMARY_IN, "D" } },
	{ { PRIMARY_OUT, "Q" } }
	},
	{ STD90, { { RDFFNX1, "RDFFNX1" },{ RDFFNX2, "RDFFNX2" }
		END_OF_DEF
	},
		3, 2,
		{ { PRIMARY_IN, "D" },{ CLOCK, "CLK" },{ PRIMARY_IN, "RETN" } },
		{ { PRIMARY_OUT, "Q" },{ PRIMARY_OUT, "QN" } }
	}

	//LEVEL SHIFTER, SHOULD BE SET, PROB:VDD, VSS NODE

};

#define ARRAY_SIZE(x) sizeof(x)/sizeof(x[0])

StdCellInfo* FindStdCellInfo(EType e, int stdType)
{
	for (int i = 0; i < ARRAY_SIZE(eInfo); i++)
	{
		if (eInfo[i].nStdType == stdType)
			for (int j = 0; eInfo[i].cells[j].e < __MAX_ENTITY; j++)
			{
				if (eInfo[i].cells[j].e == e)
					return &eInfo[i];
			}
	}
	return NULL;
}

StdCellInfo* FindStdCellInfo(char *node_name, int stdType)
{
	for (int i = 0; i < ARRAY_SIZE(eInfo); i++)
	{
		if (eInfo[i].nStdType == stdType)
			for (int j = 0; eInfo[i].cells[j].e < __MAX_ENTITY; j++)
			{
				if (strcmp(eInfo[i].cells[j].name, node_name) == 0)
					return &eInfo[i];
			}
	}
	return NULL;
}